// Mocks generated by Mockito 5.2.0 from annotations
// in pokemondo/test/features/pokemon/presentation/favourites_bloc/bloc/favourites_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemondo/core/error/failures.dart' as _i6;
import 'package:pokemondo/features/pokemon/domain/entities/pokemon.dart' as _i9;
import 'package:pokemondo/features/pokemon/domain/repositories/pokemon_repository.dart'
    as _i2;
import 'package:pokemondo/features/pokemon/domain/usecases/get_favourites.dart'
    as _i8;
import 'package:pokemondo/features/pokemon/domain/usecases/remove_from_favourites.dart'
    as _i7;
import 'package:pokemondo/features/pokemon/domain/usecases/save_to_favourites.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePokemonRepository_0 extends _i1.Fake
    implements _i2.PokemonRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [SaveToFavourites].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveToFavourites extends _i1.Mock implements _i4.SaveToFavourites {
  MockSaveToFavourites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(_i4.SaveParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, bool>>.value(
                  _FakeEither_1<_i6.Failure, bool>()))
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [RemoveFromFavourites].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFromFavourites extends _i1.Mock
    implements _i7.RemoveFromFavourites {
  MockRemoveFromFavourites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(_i7.RemoveParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, bool>>.value(
                  _FakeEither_1<_i6.Failure, bool>()))
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [GetFavourites].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavourites extends _i1.Mock implements _i8.GetFavourites {
  MockGetFavourites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.Pokemon>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i9.Pokemon>>>.value(
              _FakeEither_1<_i6.Failure, List<_i9.Pokemon>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i9.Pokemon>>>);
}
