// Mocks generated by Mockito 5.2.0 from annotations
// in pokemondo/test/features/pokemon/domain/usecases/get_pokemon_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemondo/core/error/failures.dart' as _i5;
import 'package:pokemondo/features/pokemon/domain/entities/named_pokemon.dart'
    as _i7;
import 'package:pokemondo/features/pokemon/domain/entities/pokemon.dart' as _i6;
import 'package:pokemondo/features/pokemon/domain/repositories/pokemon_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Pokemon>> getPokemon(
          _i7.NamedPokemon? namedPokemon) =>
      (super.noSuchMethod(Invocation.method(#getPokemon, [namedPokemon]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Pokemon>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Pokemon>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Pokemon>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> saveToFavourites(
          List<_i6.Pokemon>? pokemons) =>
      (super.noSuchMethod(Invocation.method(#saveToFavourites, [pokemons]),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>> getFavourites() =>
      (super.noSuchMethod(Invocation.method(#getFavourites, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Pokemon>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Pokemon>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> removeFromFavourites(int? id) =>
      (super.noSuchMethod(Invocation.method(#removeFromFavourites, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
